### ISSUE TITLE
[Bug]: Share Audio Bug Feature

### ISSUE THREAD

**Issue by gonojuarez** [OTTAA-Project/OTTAAProject#149]
### Contact Details

gonojuarez17@gmail.com

### What happened?

A bug happens when the user tries to share an audio message
Because the audio file doesn't exist.

### Version

6.7.x (Production)

### Where are you seeing the problem on?

Android

### Relevant log output

```shell
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
       at android.speech.tts.TextToSpeech.synthesizeToFile(TextToSpeech.java:1839)
       at com.stonefacesoft.ottaa.utils.shareActions.ShareAudio.prepareAudio(ShareAudio.java:88)
       at com.stonefacesoft.ottaa.utils.shareActions.ShareAudio.prepareFile(ShareAudio.java:44)
       at com.stonefacesoft.ottaa.CompartirArchivos$1.onClick(CompartirArchivos.java:115)
       at android.view.View.performClick(View.java:8160)
       at android.view.View.performClickInternal(View.java:8137)
       at android.view.View.access$3700(View.java:888)
       at android.view.View$PerformClick.run(View.java:30236)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
```
Fatal Exception: java.lang.IllegalArgumentException: Prefix string too short
       at java.io.File.createTempFile(File.java:1991)
       at java.io.File.createTempFile(File.java:2064)
       at com.stonefacesoft.ottaa.utils.Audio.AudioFileCreator.getFile(AudioFileCreator.java:57)
       at com.stonefacesoft.ottaa.utils.Audio.AudioFileCreator.createFile(AudioFileCreator.java:44)
       at com.stonefacesoft.ottaa.utils.shareActions.ShareAudio.prepareAudio(ShareAudio.java:51)
       at com.stonefacesoft.ottaa.utils.shareActions.ShareAudio.prepareFile(ShareAudio.java:44)
       at com.stonefacesoft.ottaa.CompartirArchivos$1.onClick(CompartirArchivos.java:115)
       at android.view.View.performClick(View.java:7575)
       at android.view.View.performClickInternal(View.java:7548)
       at android.view.View.access$3600(View.java:837)
       at android.view.View$PerformClick.run(View.java:28933)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8057)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gonojuarez** [comment]
Happen when the system trims the audio to create a file
